FROM ruby:3.3.0-slim

WORKDIR /rails

# Instalar dependências do sistema
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential \
    git \
    libpq-dev \
    libvips \
    nodejs \
    postgresql-client \
    redis-tools \
    && rm -rf /var/lib/apt/lists/*

# Instalar gems
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Copiar código da aplicação
COPY . .

# Expor porta
EXPOSE 3000

CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
